[package]
name = "nights_into_bins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4"
num-traits = "0.2"
itertools = "0.10"
ndarray = "0.15"
image = "0.24"
walkdir = "2.3"
